version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build:
      target: dev
      context: .
    command: poetry run uvicorn cookbook.main:app --reload --host 0.0.0.0 --port 3001
    volumes:
      - .:/app
    ports:
      - 3001:3001
volumes:
  db:
    driver: local
